import type { PackageVersionRecord } from '../package_review/types.ts';
import type {
  InstructorReport,
  InstructorReportDailyActivity,
  InstructorReportEventMix,
  InstructorReportItemActivity,
  InstructorReportScoreBucket,
  InstructorReportStudent,
  InstructorReportStudentSignal,
} from '../reports/instructor_report.ts';
import {
  type AdminNotice,
  escapeHtml,
  formatDate,
  formatDateTime,
  renderAdminLayout,
} from './layout.ts';
import { renderPackagePageNav } from './package_navigation.ts';

export function renderPackageReportsPage(input: {
  appId: string;
  appTitle: string;
  history: PackageVersionRecord[];
  report: InstructorReport;
  notice?: AdminNotice | null;
}): string {
  return renderAdminLayout({
    title: `${input.appTitle} Reports`,
    eyebrow: 'Instructor reports',
    heading: input.appTitle,
    intro: 'Learner progress from Lantern-managed attempts and attempt events.',
    activePath: '/admin/packages',
    breadcrumbs: [
      { label: 'Apps', href: '/admin/packages' },
      { label: input.appTitle, href: `/admin/packages/${input.appId}` },
      { label: 'Reports' },
    ],
    notice: input.notice ?? null,
    pageNav: renderPackagePageNav({
      appId: input.appId,
      history: input.history,
      currentSection: 'reports',
    }),
    body: input.report.summary.attemptCount === 0
      ? renderEmptyReport()
      : `${renderReportSummary(input.report)}
          ${renderClassHealthSection(input.report)}
          ${renderDailyActivitySection(input.report.dailyActivity)}
          ${renderReportInsightsSection(input.report)}
          ${renderStudentSection(input.report.students)}
          ${renderRecentAttemptsSection(input.report)}`,
  });
}

function renderEmptyReport(): string {
  return `<section class="panel">
    <div class="panel-body empty-state">
      <div class="stack">
        <p class="section-label">No learner attempts yet</p>
        <h2>Reports appear after students launch the approved app.</h2>
        <p>Lantern excludes admin preview launches here. The report uses only learner attempts, GatewayApp attempt events, local progress writes, finalization, and grade publication records from the governed runtime.</p>
      </div>
    </div>
  </section>`;
}

function renderReportSummary(report: InstructorReport): string {
  const summary = report.summary;

  return `<section class="panel">
    <div class="panel-body stack">
      <div class="panel-header">
        <div class="stack">
          <p class="section-label">Class activity</p>
          <h2>Reportable progress</h2>
          <p>Counts come from learner launches and GatewayApp events. Preview launches stay out of this report.</p>
        </div>
        <p class="micro muted">Updated ${escapeHtml(formatDateTime(report.generatedAt))}</p>
      </div>
      <div class="facts">
        ${renderFact('Learners', String(summary.learnerCount))}
        ${renderFact('Attempts', String(summary.attemptCount))}
        ${renderFact('Completed', String(summary.completedAttemptCount))}
        ${renderFact('In progress', String(summary.inProgressAttemptCount))}
        ${renderFact('Answer events', String(summary.answerEventCount))}
        ${renderFact('Progress events', String(summary.progressEventCount))}
        ${renderFact('Completion events', String(summary.completeEventCount))}
        ${renderFact('Completion rate', formatPercent(summary.completionRatePercent))}
        ${renderFact('Average score', formatPercent(summary.averageScorePercent))}
        ${renderFact('Latest activity', formatDateTime(summary.latestActivityAt))}
      </div>
    </div>
  </section>`;
}

function renderClassHealthSection(report: InstructorReport): string {
  const followUpCount = report.students.filter(
    (student) => student.signal === 'needs_follow_up',
  ).length;
  const topItem = report.itemActivity[0] ?? null;

  return `<section class="panel">
    <div class="panel-body stack">
      <div class="panel-header">
        <div class="stack">
          <p class="section-label">Class health</p>
          <h2>Instructor takeaways</h2>
          <p>These signals summarize learner progress, completion, and the activity evidence generated by this app.</p>
        </div>
      </div>
      <div class="report-health-grid">
        <div class="report-health-primary">
          ${renderCompletionMeter(report.summary.completionRatePercent)}
          <div class="stack">
            <h3>${escapeHtml(formatPercent(report.summary.completionRatePercent))} complete</h3>
            <p class="micro muted">${
    escapeHtml(
      `${report.summary.completedAttemptCount} of ${report.summary.attemptCount} learner attempts are complete.`,
    )
  }</p>
          </div>
        </div>
        <ul class="report-takeaways">
          <li><strong>${escapeHtml(String(followUpCount))}</strong> ${
    escapeHtml(
      pluralize(followUpCount, 'learner'),
    )
  } may need follow-up.</li>
          <li><strong>${
    escapeHtml(
      String(report.summary.scoredAttemptCount),
    )
  }</strong> ${
    escapeHtml(
      pluralize(report.summary.scoredAttemptCount, 'attempt'),
    )
  } produced a reportable score.</li>
          <li><strong>${
    escapeHtml(
      String(report.summary.totalEventCount),
    )
  }</strong> governed runtime ${
    escapeHtml(
      pluralize(report.summary.totalEventCount, 'event'),
    )
  } recorded across answers, progress, and completions.</li>
          <li>${renderTopItemTakeaway(topItem)}</li>
        </ul>
      </div>
    </div>
  </section>`;
}

function renderReportInsightsSection(report: InstructorReport): string {
  return `<section class="panel">
    <div class="panel-body stack">
      <div class="panel-header">
        <div class="stack">
          <p class="section-label">Learning signals</p>
          <h2>What students did</h2>
        </div>
      </div>
      <div class="report-insight-grid">
        <section class="report-insight">
          <h3>Score distribution</h3>
          ${renderScoreDistribution(report.scoreDistribution)}
        </section>
        <section class="report-insight">
          <h3>Event mix</h3>
          ${renderEventMix(report.eventMix)}
        </section>
        <section class="report-insight">
          <h3>Most practiced items</h3>
          ${renderItemActivity(report.itemActivity)}
        </section>
      </div>
    </div>
  </section>`;
}

function renderDailyActivitySection(dailyActivity: InstructorReportDailyActivity[]): string {
  return `<section class="panel">
    <div class="panel-body stack">
      <div class="panel-header">
        <div class="stack">
          <p class="section-label">Activity chart</p>
          <h2>Attempts by day</h2>
        </div>
      </div>
      ${renderAttemptBarChart(dailyActivity)}
    </div>
  </section>`;
}

function renderStudentSection(students: InstructorReportStudent[]): string {
  return `<section class="panel">
    <div class="panel-body stack">
      <div class="panel-header">
        <div class="stack">
          <p class="section-label">Learners</p>
          <h2>Student progress</h2>
        </div>
      </div>
      <div class="report-table-wrap">
        <table class="report-table">
          <thead>
            <tr>
              <th scope="col">Student</th>
              <th scope="col">Signal</th>
              <th scope="col">Attempts</th>
              <th scope="col">Completed</th>
              <th scope="col">Events</th>
              <th scope="col">Latest score</th>
              <th scope="col">Last activity</th>
            </tr>
          </thead>
          <tbody>
            ${students.map(renderStudentRow).join('')}
          </tbody>
        </table>
      </div>
    </div>
  </section>`;
}

function renderRecentAttemptsSection(report: InstructorReport): string {
  return `<section class="panel">
    <div class="panel-body stack">
      <p class="section-label">Recent attempts</p>
      <div class="line-list">
        ${
    report.recentAttempts
      .map(
        (attempt) =>
          `<article class="line-item">
              <p class="line-title">
                <span>${escapeHtml(displayAttemptUser(attempt.attempt))}</span>
                <span class="chip">${escapeHtml(formatAttemptStatus(attempt.attempt.status))}</span>
              </p>
              <p class="line-copy">${escapeHtml(attempt.attempt.packageVersion)} · ${
            escapeHtml(
              attempt.attempt.deploymentSlug,
            )
          } · ${escapeHtml(String(attempt.eventCount))} events · ${
            escapeHtml(
              String(attempt.answerEventCount),
            )
          } answers${
            attempt.scorePercent === null
              ? ''
              : ` · ${escapeHtml(formatPercent(attempt.scorePercent))}`
          }</p>
              <p class="micro muted">Started ${
            escapeHtml(
              formatDateTime(attempt.attempt.startedAt),
            )
          }; latest event ${escapeHtml(formatDateTime(attempt.latestEventAt))}</p>
            </article>`,
      )
      .join('')
  }
      </div>
    </div>
  </section>`;
}

function renderScoreDistribution(buckets: InstructorReportScoreBucket[]): string {
  return renderMeterRows(
    buckets.map((bucket) => ({
      label: bucket.label,
      value: bucket.count,
      valueLabel: pluralize(bucket.count, 'attempt'),
    })),
  );
}

function renderEventMix(eventMix: InstructorReportEventMix[]): string {
  return renderMeterRows(
    eventMix.map((event) => ({
      label: event.label,
      value: event.count,
      valueLabel: pluralize(event.count, 'event'),
    })),
  );
}

function renderItemActivity(itemActivity: InstructorReportItemActivity[]): string {
  if (itemActivity.length === 0) {
    return `<p class="micro muted">No answer events have been recorded yet.</p>`;
  }

  return renderMeterRows(
    itemActivity.map((item) => ({
      label: item.questionId,
      value: item.answerEventCount,
      valueLabel: pluralize(item.answerEventCount, 'answer'),
      detail: `latest ${formatDateTime(item.latestAnsweredAt)}`,
    })),
  );
}

function renderMeterRows(
  rows: Array<{ label: string; value: number; valueLabel: string; detail?: string }>,
): string {
  const maxValue = Math.max(1, ...rows.map((row) => row.value));

  return `<div class="report-meter-rows">
    ${
    rows
      .map((row) => {
        const width = Math.round((row.value / maxValue) * 100);

        return `<div class="report-meter-row">
          <div class="report-meter-row-copy">
            <span>${escapeHtml(row.label)}</span>
            <span>${escapeHtml(String(row.value))} ${
          escapeHtml(
            row.valueLabel,
          )
        }${row.detail ? ` · ${escapeHtml(row.detail)}` : ''}</span>
          </div>
          <div class="report-meter-track" aria-hidden="true">
            <span class="report-meter-fill" style="width: ${escapeHtml(String(width))}%"></span>
          </div>
        </div>`;
      })
      .join('')
  }
  </div>`;
}

function renderAttemptBarChart(dailyActivity: InstructorReportDailyActivity[]): string {
  const maxAttempts = Math.max(1, ...dailyActivity.map((day) => day.attemptCount));

  return `<div class="report-chart" role="img" aria-label="Learner attempts by day">
    <div class="report-chart-bars">
      ${
    dailyActivity
      .map((day) => {
        const height = Math.max(8, Math.round((day.attemptCount / maxAttempts) * 120));
        const completedHeight = day.attemptCount === 0
          ? 0
          : Math.round((day.completedAttemptCount / day.attemptCount) * height);

        return `<div class="report-chart-bar-group">
            <div class="report-chart-bar-track" title="${
          escapeHtml(
            `${day.attemptCount} attempts, ${day.completedAttemptCount} completed`,
          )
        }">
              <span class="report-chart-bar" style="height: ${height}px"></span>
              <span class="report-chart-bar-completed" style="height: ${completedHeight}px"></span>
            </div>
            <span class="report-chart-value">${escapeHtml(String(day.attemptCount))}</span>
            <span class="report-chart-label">${
          escapeHtml(
            formatDate(`${day.day}T12:00:00Z`),
          )
        }</span>
          </div>`;
      })
      .join('')
  }
    </div>
    <p class="micro muted">Blue bars show attempts. Green fill shows completed attempts.</p>
  </div>`;
}

function renderStudentRow(student: InstructorReportStudent): string {
  return `<tr>
    <th scope="row">
      <span class="report-student-name">${escapeHtml(student.displayName)}</span>
      <span class="micro muted">${
    escapeHtml(
      student.email ?? student.login ?? student.userId,
    )
  }</span>
    </th>
    <td>${renderStudentSignal(student.signal)}</td>
    <td>${escapeHtml(String(student.attemptCount))}</td>
    <td>${renderCompletionCell(student)}</td>
    <td>
      <span>${escapeHtml(String(student.totalEventCount))}</span>
      <span class="micro muted report-table-detail">${
    escapeHtml(
      `${student.answerEventCount} answers, ${student.progressEventCount} progress, ${student.completeEventCount} complete`,
    )
  }</span>
    </td>
    <td>${renderScoreCell(student.latestScorePercent)}</td>
    <td>${escapeHtml(formatDateTime(student.latestActivityAt))}</td>
  </tr>`;
}

function renderCompletionMeter(value: number): string {
  const percent = clampPercent(value);

  return `<div class="report-completion-meter" style="--report-meter-value: ${
    escapeHtml(
      String(percent),
    )
  }%;" role="img" aria-label="${escapeHtml(formatPercent(value))} completion rate">
    <span>${escapeHtml(formatPercent(value))}</span>
  </div>`;
}

function renderCompletionCell(student: InstructorReportStudent): string {
  return `<div class="report-student-metric">
    <span>${escapeHtml(String(student.completedAttemptCount))}/${
    escapeHtml(
      String(student.attemptCount),
    )
  }</span>
    <div class="report-meter-track" aria-hidden="true">
      <span class="report-meter-fill report-meter-fill-success" style="width: ${
    escapeHtml(
      String(clampPercent(student.completionRatePercent)),
    )
  }%"></span>
    </div>
  </div>`;
}

function renderScoreCell(score: number | null): string {
  if (score === null) {
    return '<span class="muted">Not scored</span>';
  }

  return `<div class="report-student-metric">
    <span>${escapeHtml(formatPercent(score))}</span>
    <div class="report-meter-track" aria-hidden="true">
      <span class="report-meter-fill" style="width: ${
    escapeHtml(
      String(clampPercent(score)),
    )
  }%"></span>
    </div>
  </div>`;
}

function renderStudentSignal(signal: InstructorReportStudentSignal): string {
  return `<span class="report-signal report-signal-${escapeHtml(signal)}">${
    escapeHtml(
      formatStudentSignal(signal),
    )
  }</span>`;
}

function renderTopItemTakeaway(item: InstructorReportItemActivity | null): string {
  if (item === null) {
    return 'No practiced item has enough answer evidence yet.';
  }

  return `<strong>${
    escapeHtml(
      item.questionId,
    )
  }</strong> is the most practiced item with ${
    escapeHtml(
      String(item.answerEventCount),
    )
  } ${escapeHtml(pluralize(item.answerEventCount, 'answer'))}.`;
}

function renderFact(label: string, value: string): string {
  return `<div class="fact">
    <span class="fact-label">${escapeHtml(label)}</span>
    <span class="fact-value">${escapeHtml(value)}</span>
  </div>`;
}

function displayAttemptUser(attempt: {
  userDisplayName: string | null;
  userLogin: string | null;
  userEmail: string | null;
  userId: string;
}): string {
  return attempt.userDisplayName ?? attempt.userLogin ?? attempt.userEmail ?? attempt.userId;
}

function formatAttemptStatus(status: string): string {
  return status
    .split('_')
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function formatStudentSignal(signal: InstructorReportStudentSignal): string {
  switch (signal) {
    case 'on_track':
      return 'On track';
    case 'in_progress':
      return 'In progress';
    case 'needs_follow_up':
      return 'Needs follow-up';
  }
}

function formatPercent(value: number | null): string {
  if (value === null) {
    return 'Not scored';
  }

  return `${Math.round(value)}%`;
}

function clampPercent(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}

function pluralize(count: number, singular: string): string {
  return count === 1 ? singular : `${singular}s`;
}
